[package]
name = "pg_linearalgebra"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg14"]
pg11 = ["pgrx/pg11", "pgrx-tests/pg11" ]
pg12 = ["pgrx/pg12", "pgrx-tests/pg12" ]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13" ]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14" ]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15" ]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16" ]
pg_test = []

[dependencies]
pgrx = "0.10.0"
pg-trunk = "0.11.3"
ndarray = "0.15"
ndarray-rand = "0.13"
ndarray-linalg = { version = "0.16.0", features = ["openblas"] }
serde_json = "1.0"

[dev-dependencies]
pgrx-tests = "=0.10.2"

[build]
script = "build.rs"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
